"""create contest

Revision ID: 1512a8979993
Revises: d3d546e27222
Create Date: 2018-07-22 01:21:44.372782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1512a8979993'
down_revision = 'd3d546e27222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('oj_name', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('oj_name'),
    sa.UniqueConstraint('site', 'contest_id', name='_site_contest_id_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    # ### end Alembic commands ###
