"""empty message

Revision ID: 04d24688e36b
Revises: 8c6bd271f7b5
Create Date: 2018-08-08 00:42:27.922105

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '04d24688e36b'
down_revision = '8c6bd271f7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problems', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oj_name', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('problems', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
