"""empty message

Revision ID: 8c6bd271f7b5
Revises: 095c54d34f42
Create Date: 2018-08-07 21:56:48.493125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6bd271f7b5'
down_revision = '095c54d34f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('oj_name', sa.String(), nullable=False),
    sa.Column('problem_id', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('source_code', sa.String(), nullable=False),
    sa.Column('share', sa.Boolean(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('exe_time', sa.Integer(), nullable=True),
    sa.Column('exe_mem', sa.Integer(), nullable=True),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oj_name', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=False),
    sa.Column('contest_id', sa.String(), nullable=False),
    sa.Column('problems', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    op.drop_table('contest_submissions')
    # ### end Alembic commands ###
